// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking_service.proto

package rs.raf.pds.v5.z2.gRPC;

public interface UserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
