// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking_service.proto

package rs.raf.pds.v5.z2.gRPC;

public final class BookingServiceOuterClass {
  private BookingServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BookingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BookingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CancelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CancelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CancelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CancelResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookingInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BookingInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025booking_service.proto\"@\n\016BookingReques" +
      "t\022\017\n\007user_id\030\001 \001(\t\022\017\n\007room_id\030\002 \001(\t\022\014\n\004d" +
      "ate\030\003 \001(\t\"3\n\017BookingResponse\022\017\n\007success\030" +
      "\001 \001(\010\022\017\n\007message\030\002 \001(\t\"#\n\rCancelRequest\022" +
      "\022\n\nbooking_id\030\001 \001(\t\"2\n\016CancelResponse\022\017\n" +
      "\007success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\"\036\n\013UserR" +
      "equest\022\017\n\007user_id\030\001 \001(\t\"P\n\013BookingInfo\022\022" +
      "\n\nbooking_id\030\001 \001(\t\022\017\n\007room_id\030\002 \001(\t\022\014\n\004d" +
      "ate\030\003 \001(\t\022\016\n\006status\030\004 \001(\t2\247\001\n\016BookingSer" +
      "vice\0222\n\013MakeBooking\022\017.BookingRequest\032\020.B" +
      "ookingResponse\"\000\0222\n\rCancelBooking\022\016.Canc" +
      "elRequest\032\017.CancelResponse\"\000\022-\n\013GetBooki" +
      "ngs\022\014.UserRequest\032\014.BookingInfo\"\0000\001B\031\n\025r" +
      "s.raf.pds.v5.z2.gRPCP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_BookingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BookingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BookingRequest_descriptor,
        new java.lang.String[] { "UserId", "RoomId", "Date", });
    internal_static_BookingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BookingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BookingResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_CancelRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CancelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CancelRequest_descriptor,
        new java.lang.String[] { "BookingId", });
    internal_static_CancelResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_CancelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CancelResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_UserRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_UserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_BookingInfo_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_BookingInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BookingInfo_descriptor,
        new java.lang.String[] { "BookingId", "RoomId", "Date", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
