// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking_service.proto

package rs.raf.pds.v5.z2.gRPC;

public interface CancelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CancelRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string booking_id = 1;</code>
   * @return The bookingId.
   */
  java.lang.String getBookingId();
  /**
   * <code>string booking_id = 1;</code>
   * @return The bytes for bookingId.
   */
  com.google.protobuf.ByteString
      getBookingIdBytes();
}
